---
title: "Demos"
---

| Demo   | Date    | Title              | Demo file                            |
|--------|---------|--------------------|--------------------------------------|
| 0      | Jan 14  | Into the tidyverse | [HTML](demos/00-into-tidyverse.qmd)  |
| 1      | Jan 16  | Building an Expected Goals Model | [HTML](demos/01-logit-expected-goals.qmd)  |
| 2      | Jan 21  | Calibration and Cross-Validation | [HTML](demos/02-calibration-cv.qmd)  |
| 3      | Jan 23  | Multinomial Logistic Regression for Expected Points | [HTML](demos/03-multinom-logit.qmd)  |
| 4a      | Jan 28  | Exploring Expected Points Added | [HTML](demos/04a-epa.qmd)  |
| 4b      | Jan 28  | Completion Percentage Over Expectation | [HTML](demos/04b-cpoe.qmd)  |
| 5      | Jan 30  | Intro to multilevel modeling | [HTML](demos/05-intro-multilevel-models.qmd)  |
| 6      | Feb 4  | Varying intercepts and slopes | [HTML](demos/06-varying-ints-slopes.qmd)  |
| 7      | Feb 6  | Nested and crossed random effects | [HTML](demos/07-nested-crossed-effects.qmd)  |
| 8      | Feb 11  | Random effects and pooling | [HTML](demos/08-random-effects-pooling.qmd)  |
| 9      | Feb 13  | Uncertainty about random effects | [HTML](demos/09-random-effects-uncertainty.qmd)  |
| 10      | Feb 18  | Introduction to Bayes with a Binomial model | [HTML](demos/10-intro-bayes.qmd)  |
| 11      | Feb 20  | Beta-Binomial model for Caitlin Clark's rookie season | [HTML](demos/11-beta-binomial.qmd)  |
| 12      | Feb 25  | Introduction to Regularized Adjusted Plus-Minus (RAPM) | [HTML](demos/12-intro-rapm.qmd)  |
| 13      | Mar 11  | Methods for Approximating the Posterior | [HTML](demos/13-posterior-approx.qmd)  |
| 14      | Mar 18  | Introduction to Stan | [HTML](demos/14-intro-stan.qmd)  |
| 15      | Mar 20  | Bayesian RAPM in Stan | [HTML](demos/15-bayes-rapm-stan.qmd)  |
| 16      | Mar 27  | Modeling team ratings and posterior predictions | [HTML](demos/16-team-ratings.qmd)  |
| 17      | Apr 1  | Bayesian model comparison | [HTML](demos/17-bayes-model-comp.qmd)  |
| 18      | Apr 8  | Introduction to Elo ratings | [HTML](demos/18-elo-ratings.qmd)  |
| 19      | Apr 10  | Bayesian state-space model for NFL team ratings | [HTML](demos/19-bayes-state-space.qmd)  |
