---
title: "Lectures"
---

| Lecture   | Date    | Title                                | Links to slides                              |
|-----------|---------|--------------------------------------|----------------------------------------|
| 1         | Jan 14  | Intro and Big Ideas in Sports Analytics | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/11E6WuPEUj_knejOPa79LmPn5VVd0daxDs9WpFtYH_po/edit?usp=sharing)        |
| 2         | Jan 16  | Building an Expected Goals Model | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/161QTz_uja0G-DiFy6FwIuODhZWBJ1EjmBrknCFheX1k/edit?usp=sharing)        |
| 3         | Jan 21  | Building an Expected Goals Model (Cont.) | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/1vk8DwGvKSV_Ln8-lUmDSiij8EczrrDBzW3xEGIrvChI/edit?usp=sharing)        |
| 4         | Jan 23  | Building an Expected Points Model | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/1iABRMbNXHKkstzU_fHEMexllLkeS2QedAgwouh7IsQQ/edit?usp=sharing)        |
| 5         | Jan 28  | Expected Points (cont.) and CPOE | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/15CRgNs4CQLRGB_QGjNxlWAMKm-QeaZ9D2c0wsed5_FA/edit?usp=sharing)        |
| 6         | Jan 30  | CPOE and introduction to multilevel modeling | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/1o6KkFjaMnM8UDEhwctfC6GYX1BLE_-clHpCVCSJJysk/edit?usp=sharing)        |
| 7         | Feb 4  | Varying intercepts and slopes | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/1nEvsahM5x0vGYFaBs8_OLvhxe4LvrIVdIn7oJ1HCtHQ/edit?usp=sharing)        |
| 8         | Feb 6  | Nested and crossed random effects | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/156Twdfz9Q1vuyeisS_HseqwChmJeZv_wvAhfqBDzz_E/edit?usp=sharing)        |
| 9         | Feb 11  | Model fitting and random effects | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/17CjAnLI6XoIGZUvQ23kbRkLuf8AyNK3A8mKZNAaFzd0/edit?usp=sharing)        |
| 10        | Feb 13  | Random effects pooling and uncertainty | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/1TWo74cCBujGRnwuCNS2eKyCc07LU_gDNYTb9b9UpA3o/edit?usp=sharing)        |
| 11        | Feb 18  | Intro to Bayesian thinking | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/1PItDAxqKlMWNxTjCLY8OoXBDPs7mg6mfSkHarG0ivXA/edit?usp=sharing)        |
| 12        | Feb 20  | Beta-Binomial Model and Conjugate Priors | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/1KWDuu-ofK7ABTO81dqRXwZJ-KUEk0wVjz1KNxSDp4oQ/edit?usp=sharing)        |
| 13        | Feb 25  | Intro to Regularized Adjusted Plus-Minus Models | [Google slides (requires CMU email)](https://docs.google.com/presentation/d/1TtWdsG2oWeUx_-uYLVmG9WBXp3oTkctVr01bYl4aT0s/edit?usp=sharing)        |


